# Pull official base image:
FROM python:3.9.6-alpine

# Set work directory:
WORKDIR /code/

# Set environment variables:
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install dependencies:
RUN pip install --upgrade pip
COPY requirements.txt /code/
RUN pip install -r requirements.txt

# Copy project:
COPY . /code/
